version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      allow:
          - dependency-name: "@apst/biome"
          - dependency-name: "@apst/tsconfig"
          - dependency-name: "@biomejs/biome"
          - dependency-name: "@microsoft/api-extractor"
          - dependency-name: "@rsbuild/plugin-react"
          - dependency-name: "@rslib/core"
          - dependency-name: "typedoc"
          - dependency-name: "typedoc-plugin-markdown"
          - dependency-name: "typescript"
